# pubspec.yaml

name: party_dice
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  flex_color_picker: ^3.4.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  random_x: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/icon/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#282828"
    theme_color: "#673AB7"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"