name: neubrutalism_party_dice
description: "Party Dice Game"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0-180.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  patterns_canvas: ^0.5.0
  flutter_screenutil: ^5.9.3
  flutter_3d_controller: ^1.3.1
  another_flutter_splash_screen: ^1.2.1
  flutter_login: ^5.0.0
  flutter_native_splash: ^2.4.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1
  firebase_analytics: ^10.8.0
  cloud_firestore: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/premium_dice.png
    - assets/images/custom_actions.png
    - assets/images/party_themes.png
    - assets/images/avatars.png
    - assets/images/extra_time.png
    - assets/images/pro_features.png
    - assets/images/splash_screen.png
    - assets/images/partydicelogo.png
#    - assets/3d/dice.glb
    - assets/google_fonts/Roboto_Condensed/static/RobotoCondensed-Regular.ttf
    - assets/google_fonts/Roboto_Condensed/static/RobotoCondensed-Bold.ttf
    - assets/google_fonts/Satisfy/Satisfy-Regular.ttf
    - assets/google_fonts/Rampart_One/RampartOne-Regular.ttf
    - assets/google_fonts/Mochiy_Pop_One/MochiyPopOne-Regular.ttf
    - assets/google_fonts/Bungee/Bungee-Regular.ttf
    - assets/google_fonts/Black_Ops_One/BlackOpsOne-Regular.ttf

  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: assets/google_fonts/Roboto_Condensed/static/RobotoCondensed-Regular.ttf
        - asset: assets/google_fonts/Roboto_Condensed/static/RobotoCondensed-Bold.ttf
          weight: 700
    - family: MochiyPopOne
      fonts:
        - asset: assets/google_fonts/Mochiy_Pop_One/MochiyPopOne-Regular.ttf
    - family: Satisfy
      fonts:
        - asset: assets/google_fonts/Satisfy/Satisfy-Regular.ttf
    - family: Bungee
      fonts:
        - asset: assets/google_fonts/Bungee/Bungee-Regular.ttf
    - family: RampartOne
      fonts:
        - asset: assets/google_fonts/Rampart_One/RampartOne-Regular.ttf
    - family: BlackOpsOne
      fonts:
        - asset: assets/google_fonts/Black_Ops_One/BlackOpsOne-Regular.ttf
