// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFPvQy_6p15l-UKswpGfYTeH0Dm6mQjs0',
    appId: '1:489495484731:web:42ade37c51b3d37c923f1e',
    messagingSenderId: '489495484731',
    projectId: 'partydice-283d9',
    authDomain: 'partydice-283d9.firebaseapp.com',
    storageBucket: 'partydice-283d9.appspot.com',
    measurementId: 'G-3TLME7J931',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApv3qncf0ZUPaCRMjzgu2IM6m6vcaw_4o',
    appId: '1:489495484731:android:9a5b9145feb35c35923f1e',
    messagingSenderId: '489495484731',
    projectId: 'partydice-283d9',
    storageBucket: 'partydice-283d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk3EDV8JmAmR4ktSOtK1qbn4jvoFE-5IY',
    appId: '1:489495484731:ios:1398e4f3cdcd1028923f1e',
    messagingSenderId: '489495484731',
    projectId: 'partydice-283d9',
    storageBucket: 'partydice-283d9.appspot.com',
    iosBundleId: 'com.codecodes.partydice.neubrutalismPartyDice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk3EDV8JmAmR4ktSOtK1qbn4jvoFE-5IY',
    appId: '1:489495484731:ios:1398e4f3cdcd1028923f1e',
    messagingSenderId: '489495484731',
    projectId: 'partydice-283d9',
    storageBucket: 'partydice-283d9.appspot.com',
    iosBundleId: 'com.codecodes.partydice.neubrutalismPartyDice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFPvQy_6p15l-UKswpGfYTeH0Dm6mQjs0',
    appId: '1:489495484731:web:71f5ec38fdb53124923f1e',
    messagingSenderId: '489495484731',
    projectId: 'partydice-283d9',
    authDomain: 'partydice-283d9.firebaseapp.com',
    storageBucket: 'partydice-283d9.appspot.com',
    measurementId: 'G-XV04P0PSQ1',
  );

}